/*
 * generated by Xtext
 */
package org.xtext.assignment1.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.assignment1.services.EinKauflistGrammarAccess;

public class EinKauflistParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EinKauflistGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.assignment1.parser.antlr.internal.InternalEinKauflistParser createParser(XtextTokenStream stream) {
		return new org.xtext.assignment1.parser.antlr.internal.InternalEinKauflistParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Buyticket";
	}
	
	public EinKauflistGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EinKauflistGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
