/*
 * generated by Xtext
 */
package org.xtext.assignment1.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.assignment1.services.EinKauflistGrammarAccess;

public class EinKauflistParser extends AbstractContentAssistParser {
	
	@Inject
	private EinKauflistGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.assignment1.ui.contentassist.antlr.internal.InternalEinKauflistParser createParser() {
		org.xtext.assignment1.ui.contentassist.antlr.internal.InternalEinKauflistParser result = new org.xtext.assignment1.ui.contentassist.antlr.internal.InternalEinKauflistParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBuyticketAccess().getGroup(), "rule__Buyticket__Group__0");
					put(grammarAccess.getCategoryAccess().getGroup(), "rule__Category__Group__0");
					put(grammarAccess.getCategoryAccess().getGroup_2(), "rule__Category__Group_2__0");
					put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
					put(grammarAccess.getBuyticketAccess().getCategoryAssignment_1(), "rule__Buyticket__CategoryAssignment_1");
					put(grammarAccess.getCategoryAccess().getCategoryNameAssignment_1(), "rule__Category__CategoryNameAssignment_1");
					put(grammarAccess.getCategoryAccess().getItemsAssignment_2_1(), "rule__Category__ItemsAssignment_2_1");
					put(grammarAccess.getItemAccess().getItemNameAssignment_0(), "rule__Item__ItemNameAssignment_0");
					put(grammarAccess.getItemAccess().getPriceAssignment_1(), "rule__Item__PriceAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.assignment1.ui.contentassist.antlr.internal.InternalEinKauflistParser typedParser = (org.xtext.assignment1.ui.contentassist.antlr.internal.InternalEinKauflistParser) parser;
			typedParser.entryRuleBuyticket();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EinKauflistGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EinKauflistGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
