/*
 * generated by Xtext
 */
package org.xtext.assignment1;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EinKauflistRuntimeModule extends org.xtext.assignment1.AbstractEinKauflistRuntimeModule {

}
