/*
 * generated by Xtext
 */
package org.xtext.assignment1;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EinKauflistUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.assignment1.ui.internal.EinKauflistActivator.getInstance().getInjector("org.xtext.assignment1.EinKauflist");
	}
	
}
