/**
 * generated by Xtext
 */
package org.xtext.assignment1.validation;

import org.xtext.assignment1.validation.AbstractEinKauflistValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EinKauflistValidator extends AbstractEinKauflistValidator {
}
