/**
 * generated by Xtext
 */
package org.xtext.assignment1.ui.contentassist;

import org.xtext.assignment1.ui.contentassist.AbstractEinKauflistProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EinKauflistProposalProvider extends AbstractEinKauflistProposalProvider {
}
