/*
 * generated by Xtext
 */
package org.xtext.assignment1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EinKauflistUiModule extends org.xtext.assignment1.ui.AbstractEinKauflistUiModule {
	public EinKauflistUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
