/*
 * generated by Xtext
 */
package org.xtext.assignment1.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.assignment1.ui.internal.EinKauflistActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EinKauflistExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EinKauflistActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EinKauflistActivator.getInstance().getInjector(EinKauflistActivator.ORG_XTEXT_ASSIGNMENT1_EINKAUFLIST);
	}
	
}
